## COMBINE THE MENU ITEMS AND ORDER DETAILS TABLES INTO A SINGLE TABLE.

SELECT *
FROM menu_items;

SELECT *
FROM order_details;

SELECT * 
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID;


## WHAT ARE THE LEAST AND MOST ORDERED ITEMS? WHAT CATEGORIES WERE THEY IN.

SELECT item_name, COUNT(order_details_id) AS NUM_PURCHASES
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID
 GROUP BY item_name
 order by NUM_PURCHASES;
 # LEAST ORDERED ITEM
 
 SELECT item_name, COUNT(order_details_id) AS NUM_PURCHASES
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID
 GROUP BY item_name
 order by NUM_PURCHASES DESC;
 # MOST ORDERED ITEMS
 
  SELECT item_name, category, COUNT(order_details_id) AS NUM_PURCHASES
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID
 GROUP BY item_name, category
 order by NUM_PURCHASES DESC;
 # CATEGORIES THEY BELONG
 
## WHAT ARE THE TOP 5 ORDERS THAT SPENT THE MOST MONEY?

SELECT ORDER_ID, SUM(PRICE) AS TOTAL_SPEND
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID
GROUP BY  order_id
ORDER BY TOTAL_SPEND DESC
LIMIT 5;


## VIEW THE DETAILS OF THE HIGHEST SPEND ORDER. WHAT INSIGHTS CAN YOU GATHER FROM THE RESULTS.

SELECT category, COUNT(item_id) AS NUMITEMS
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID
 WHERE ORDER_ID = 440
 GROUP BY category;
 
 
## VIEW THE DETAILS OF THE TOP 5 HIGHEST SPEND ORDERS. WHAT INSIGHTS CAN YOU GATHER FROM THE RESULTS?

SELECT order_id, category, COUNT(item_id) AS NUMITEMS
FROM order_details OD LEFT JOIN menu_items MI 
 ON OD.ITEM_ID = MI.MENU_ITEM_ID
 WHERE ORDER_ID IN (440, 2075, 1957, 1957, 2675)
 GROUP BY order_id, category;
 
